name: lmix-deploy

services:
  lmix:
    container_name: lmix
    image: ghcr.io/michaelschmidle/lmix:latest
    environment:
      - SUPABASE_URL=http://kong:8000
      - SUPABASE_KEY=${ANON_KEY}
      - SUPABASE_DB_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-postgres}
      - NODE_ENV=production
    ports:
      - "${LMIX_PORT:-5649}:3000"
    depends_on:
      db:
        condition: service_healthy
      kong:
        condition: service_started
    restart: unless-stopped

  # Override studio port to avoid conflicts
  studio:
    ports:
      - "${STUDIO_PORT:-7883}:3000"

  # Override kong port to avoid conflicts
  kong:
    ports:
      - "${KONG_HTTP_PORT:-5664}:8000/tcp"
      - "${KONG_HTTPS_PORT:-56647}:8443/tcp"
